### PR TITLE
Draw background only on action box

### LINKED ISSUE #2: NPE when swiping on the side without actions
Hello,

NPE happens when swiping the side without any actions. It's little bit harder to trigger when `swipeThreshold=40.dp` but it still crashes when item is dragged `40.dp`. With `swipeThreshold=1.dp` it crashes right away when swipe starts.

``` 
java.lang.NullPointerException
    at me.saket.swipe.SwipeableActionsBoxKt$SwipeableActionsBox$1.invoke(SwipeableActionsBox.kt:88)
    at me.saket.swipe.SwipeableActionsBoxKt$SwipeableActionsBox$1.invoke(SwipeableActionsBox.kt:56)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
    at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
    at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
```

https://user-images.githubusercontent.com/5840013/166129826-b99f6c11-efff-4d4d-b68d-1347ba5e6f8b.mp4

### LINKED ISSUE #4: Support for content without background
Currently, when content inside `SwipeableActionsBox` doesn't have any background or has translucent background color, `backgroundUntilSwipeThreshold` or swiped actions background is visible.

With `backgroundUntilSwipeThreshold=Color.Transparent` and content without background, it looks like this when swipe threshold is reached: 
Screen Shot 2022-04-30 at 20 14 31

### PR DESCRIPTION
**Pull request by alashow**
Not sure if this is best implementation but it's working.

Resolves #4 

Also fixes #2

### CODE REVIEW

**Comment by alashow** [comment]
Couldn't run/check paparazzi tests because it's not working on my machine, throwing this error: 
```
SEVERE: broken: Native layoutlib failed to load
java.lang.UnsatisfiedLinkError: Can't load library: /Users/alashov/.gradle/caches/transforms-3/ea0b7f66c989590baafb23b3b92901e4/transformed/layoutlib-native-macarm-2021.1.1-573f070/data/mac/lib64/libandroid_runtime.dylib
``` 

Seems like related to https://github.com/cashapp/paparazzi/pull/375/

**Comment by saket** [comment]
~~Let me see if I can paparazzi work again.~~ Done on `trunk`!

File: swipe/src/main/kotlin/me/saket/swipe/SwipeableActionsBox.kt [hunk 1]
```diff
@@ -51,7 +51,7 @@ fun SwipeableActionsBox(
   startActions: List<SwipeAction> = emptyList(),
   endActions: List<SwipeAction> = emptyList(),
   swipeThreshold: Dp = 40.dp,
-  backgroundUntilSwipeThreshold: Color = Color.DarkGray,
+  backgroundUntilSwipeThreshold: Color = Color.Transparent,
```
Comment (saket) [inline swipe/src/main/kotlin/me/saket/swipe/SwipeableActionsBox.kt]: I'd leave this as-is, mostly because this would be a breaking change for existing usages.

**Review by saket — APPROVED** [review]
Looks great, thank you! 

I added snapshot tests and removed https://github.com/saket/swipe/pull/5/commits/357f3c9f756d9f37f6b620d37bbdd7d844832eb5 because it was a breaking change.

**Comment by saket** [comment]
Uhhh my changes aren't showing up on your branch. Trying again…
