### PR TITLE
fix: icon placement in rtl layouts

### LINKED ISSUE #32: Issue with LayoutDirection.
When i set the CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl) {}
This issue occurs, 

Video link:
https://github.com/user-attachments/assets/63e8941c-d627-4661-a5fb-4d838a0ca242

### PR DESCRIPTION
**Pull request by JunkFood02**
Fix #32 

Context: The offsets from swipings are absolute, so the placement of icons should be as well

### CODE REVIEW

**Comment by abdullahalhakimi** [comment]
great this commit solved the issue i had

**Comment by JunkFood02** [comment]
ping @saket for reviewing 🤞

**Comment by Lukaszz112** [comment]
@saket bump, can u merge it?

**Review by saket — APPROVED** [review]
Thank you, and apologies for not reviewing this earlier!

File: library/src/commonMain/kotlin/me/saket/swipe/SwipeableActionsBox.kt [hunk 1]
```diff
@@ -125,11 +125,11 @@ private fun ActionIconBox(
         layout(width = placeable.width, height = placeable.height) {
           // Align icon with the left/right edge of the content being swiped.
           val iconOffset = if (action.isOnRightSide) constraints.maxWidth + offset else offset - placeable.width
-          placeable.placeRelative(x = iconOffset.roundToInt(), y = 0)
+          placeable.place(x = iconOffset.roundToInt(), y = 0)
         }
       }
       .background(color = backgroundColor),
-    horizontalArrangement = if (action.isOnRightSide) Arrangement.Start else Arrangement.End,
+    horizontalArrangement = if (action.isOnRightSide) Arrangement.Absolute.Left else Arrangement.Absolute.Right,
```
Comment (saket) [inline library/src/commonMain/kotlin/me/saket/swipe/SwipeableActionsBox.kt:132]: Let's add a screenshot test to verify this? Here are some examples: https://github.com/saket/swipe/blob/trunk/library/src/test/kotlin/me/saket/swipe/SwipeableActionsBoxTest.kt#L43

Comment (JunkFood02) [reply library/src/commonMain/kotlin/me/saket/swipe/SwipeableActionsBox.kt:132]: Not sure if I did this correctly. Please take another look!

Comment (saket) [reply library/src/commonMain/kotlin/me/saket/swipe/SwipeableActionsBox.kt:132]: Yep this looks good, thank you!

**Review by saket — APPROVED** [review]
